# Metadata
parent_config: null
description: "This is the configuration used by default."

# Polygon generation
x_min: -100
x_max: 100
y_min: -100
y_max: 100
n_range: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 50]
radius_range: [0.5, 1, 4, 32, 128]
