# Metadata
parent_config: null
description: "This is the configuration used by default."

# General
project_name: "Cartesius"
seed: null
train: True
test: True

# Paths
save_dir: "results"
ckpt: null
val_set_file: "valset.json"
test_set_file: "testset.json"

# Model
model_name: "transformer"
d_model: 128
max_seq_len: 256
n_heads: 8
d_ff: 256
dropout: 0
activation: "gelu"
n_layers: 3

# Tasks
tasks: ["area", "perimeter"]
tasks_scales: [100, 2]
task_d_ff: 256
task_dropout: 0.1

# Training
lr: 3e-5
auto_lr_find: True
batch_size: 64
n_batch_per_epoch: 1000
grad_clip: 40.0
max_time: "00:12:00:00"   # Maximum 12h of training
n_workers: 8

# Polygon generation
x_min: -100
x_max: 100
y_min: -100
y_max: 100
n_range: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 50]
radius_range: [0.5, 1, 4, 32, 128]

# Data handling
transforms: ["norm_pos", "norm_scale"]
tokenizer: "transformer"
