# Metadata
parent_config: "transformer.yaml"
description: "Best configuration to train a basic graph-based model."

# Model
model_name: "graph"
d_model: 64
d_ff: 512
dropout: 0.1
n_layers: 12

# Training
lr: 3e-4

# Data handling
tokenizer: "graph"
