# Metadata
parent_config: "default.yaml"
description: "Best configuration to train a SE(3)-Transformer."

# Model
model_name: "se3"
d_model: 128
n_heads: 2
n_layers: 1

# Training
lr: 1e-4
auto_lr_find: False
n_batch_per_epoch: 5000
