# Metadata
parent_config: "transformer_static_scale.yaml"
description: "Transformer configuration with static scale, but use a LR scheduler during training."

# Optimizer & LR Scheduler
scheduler: "cosannwarm"
