# Metadata
parent_config: "transformer.yaml"
description: "Transformer configuration with static scale, but use max pooling instead of taking the first token as representation of the polygon."

# Model
pooling: "max"
